In [17]:
import pandas as pd

In [18]:
house=pd.read_excel("Bengaluru_House_Data.xlsx")

In [19]:
house.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,2026-12-19 00:00:00,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [27]:
len(house.area_type.unique())

4

In [25]:
len(house.availability.unique())

81

In [22]:
house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [26]:
len(house.location.unique())

1295

In [29]:
len(house.society.unique())

2689

In [30]:
house.drop(["availability","location","society"],axis=1,inplace=True)

In [32]:
house.head()

              area_type       size total_sqft  bath  balcony   price
0  Super built-up  Area      2 BHK       1056   2.0      1.0   39.07
1            Plot  Area  4 Bedroom       2600   5.0      3.0  120.00
2        Built-up  Area      3 BHK       1440   2.0      3.0   62.00
3  Super built-up  Area      3 BHK       1521   3.0      1.0   95.00
4  Super built-up  Area      2 BHK       1200   2.0      1.0   51.00