In [1]:
import pandas as pd

In [2]:
house=pd.read_excel("Bengaluru_House_Data.xlsx")

In [3]:
house.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,2026-12-19 00:00:00,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [4]:
len(house.area_type.unique())

4

In [5]:
len(house.availability.unique())

81

In [6]:
house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [7]:
len(house.location.unique())

1295

In [8]:
len(house.society.unique())

2689

In [9]:
house.drop(["availability","location","society"],axis=1,inplace=True)

In [10]:
house.head()

              area_type       size total_sqft  bath  balcony   price
0  Super built-up  Area      2 BHK       1056   2.0      1.0   39.07
1            Plot  Area  4 Bedroom       2600   5.0      3.0  120.00
2        Built-up  Area      3 BHK       1440   2.0      3.0   62.00
3  Super built-up  Area      3 BHK       1521   3.0      1.0   95.00
4  Super built-up  Area      2 BHK       1200   2.0      1.0   51.00

In [11]:
house.isna().sum()

area_type       0
size           16
total_sqft      0
bath           73
balcony       609
price           0
dtype: int64

In [12]:
house.fillna({"size":house['size'].mode()[0],
             "bath":house.bath.median(),
             "balcony":0},inplace=True)

In [13]:
house["BHK"]=house["size"].apply(lambda x:x.split(" ")[0]).astype(int)

In [14]:
house.head()

              area_type       size total_sqft  bath  balcony   price  BHK
0  Super built-up  Area      2 BHK       1056   2.0      1.0   39.07    2
1            Plot  Area  4 Bedroom       2600   5.0      3.0  120.00    4
2        Built-up  Area      3 BHK       1440   2.0      3.0   62.00    3
3  Super built-up  Area      3 BHK       1521   3.0      1.0   95.00    3
4  Super built-up  Area      2 BHK       1200   2.0      1.0   51.00    2

In [15]:
house.drop("size",axis=1,inplace=True)

In [16]:
house.total_sqft.unique()

array([1056, 2600, 1440, ..., '1133 - 1384', 774, 4689],
      shape=(2117,), dtype=object)

In [17]:
house=house[house.total_sqft.astype(str).str.isnumeric()]

In [18]:
house.total_sqft=house.total_sqft.astype(float)

In [19]:
from sklearn.preprocessing import OneHotEncoder,LabelEncoder

In [20]:
ohe=OneHotEncoder()

In [21]:
area_type_encoded=ohe.fit_transform(house[["area_type"]]).toarray()

In [22]:
area_type_encoded=pd.DataFrame(area_type_encoded,columns=ohe.get_feature_names_out())

In [23]:
house=pd.concat([house,area_type_encoded],axis=1)

In [24]:
house.drop("area_type",axis=1,inplace=True)

In [25]:
house.head()

,total_sqft,bath,balcony,price,BHK,area_type_Built-up Area,area_type_Carpet Area,area_type_Plot Area,area_type_Super built-up Area
0,1056.0,2.0,1.0,39.07,2.0,0.0,0.0,0.0,1.0
1,2600.0,5.0,3.0,120.00,4.0,0.0,0.0,1.0,0.0
2,1440.0,2.0,3.0,62.00,3.0,1.0,0.0,0.0,0.0
3,1521.0,3.0,1.0,95.00,3.0,0.0,0.0,0.0,1.0
4,1200.0,2.0,1.0,51.00,2.0,0.0,0.0,0.0,1.0

In [26]:
house.corr()

,total_sqft,bath,balcony,price,BHK,area_type_Built-up Area,area_type_Carpet Area,area_type_Plot Area,area_type_Super built-up Area
total_sqft,1.000000,0.385146,0.066594,0.572146,0.340910,-0.005344,0.009530,-0.009032,0.009751
bath,0.385146,1.000000,0.072046,0.452533,0.898222,0.002636,0.005092,0.005335,-0.006985
balcony,0.066594,0.072046,1.000000,0.019070,0.066301,0.003549,0.013315,0.001838,-0.006345
price,0.572146,0.452533,0.019070,1.000000,0.394508,-0.000221,-0.001641,-0.003407,0.003017
BHK,0.340910,0.898222,0.066301,0.394508,1.000000,0.005831,0.002875,0.013077,-0.015127
area_type_Built-up Area,-0.005344,0.002636,0.003549,-0.000221,0.005831,1.000000,-0.035177,-0.202072,-0.656985
area_type_Carpet Area,0.009530,0.005092,0.013315,-0.001641,0.002875,-0.035177,1.000000,-0.031580,-0.102673
area_type_Plot Area,-0.009032,0.005335,0.001838,-0.003407,0.013077,-0.202072,-0.031580,1.000000,-0.589790
area_type_Super built-up Area,0.009751,-0.006985,-0.006345,0.003017,-0.015127,-0.656985,-0.102673,-0.589790,1.000000

### Split Data

In [27]:
house.dropna(inplace=True)

In [28]:
house.columns

Index(['total_sqft', 'bath', 'balcony', 'price', 'BHK',
       'area_type_Built-up  Area', 'area_type_Carpet  Area',
       'area_type_Plot  Area', 'area_type_Super built-up  Area'],
      dtype='object')

In [29]:
X=house.drop(["price"],axis=1)
y=house.price

In [30]:
X.shape

(12659, 8)

In [31]:
y.shape

(12659,)

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=93)

### Feature Scaling

In [34]:
from sklearn.preprocessing import StandardScaler

In [35]:
sc=StandardScaler()

In [36]:
sc.fit(X_train)

StandardScaler()

In [37]:
X_train=sc.transform(X_train)
X_test=sc.transform(X_test)

In [38]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_absolute_error

In [39]:
#training 
model =LinearRegression()

In [40]:
model.fit(X_train,y_train)

LinearRegression()

In [41]:
y_pred_train=model.predict(X_train)

In [42]:
r2_score(y_train,y_pred_train)

0.3731471230638379

In [43]:
mean_absolute_error(y_train,y_pred_train)

46.245482234095064

In [44]:
y_pred_test=model.predict(X_test)

In [45]:
r2_score(y_test,y_pred_test)

0.4332794552287753

In [46]:
mean_absolute_error(y_test,y_pred_test)

43.901923706202005

### Polynomial Linear Regression- ML Model Training

In [47]:
from sklearn.preprocessing import PolynomialFeatures

### Checking Data

In [48]:
d=pd.DataFrame({"x1":[23,54,56,78,12,54],
               "x2":[34.4,65.2,56,98,23,45]})
# d=m1*x1 + m2*x2

In [49]:
poly_reg=PolynomialFeatures(degree=2)
poly_reg.fit(d)
td=poly_reg.transform(d)

In [50]:
columns=poly_reg.get_feature_names_out()
df=pd.DataFrame(data=td,columns=columns)
df

     1    x1    x2    x1^2   x1 x2     x2^2
0  1.0  23.0  34.4   529.0   791.2  1183.36
1  1.0  54.0  65.2  2916.0  3520.8  4251.04
2  1.0  56.0  56.0  3136.0  3136.0  3136.00
3  1.0  78.0  98.0  6084.0  7644.0  9604.00
4  1.0  12.0  23.0   144.0   276.0   529.00
5  1.0  54.0  45.0  2916.0  2430.0  2025.00

### Experiment Data

In [87]:
poly_reg=PolynomialFeatures(degree=2)
poly_reg.fit(X_train)
X_train_poly=poly_reg.transform(X_train)
X_test_poly=poly_reg.transform(X_test)

In [88]:
X_train_poly.shape,X_test_poly.shape

((9494, 45), (3165, 45))

In [89]:
lr=LinearRegression()

In [90]:
lr.fit(X_train_poly,y_train)

LinearRegression()

In [91]:
lr.score(X_train_poly,y_train)

0.537547366495904

In [92]:
lr.score(X_test_poly,y_test)

0.4709508819998588

In [93]:
y_pred_train=lr.predict(X_train_poly)

In [94]:
y_pred_test=lr.predict(X_test_poly)

In [96]:
r2_score(y_train,y_pred_train)

0.537547366495904