In [82]:
import pandas as pd
from sklearn.datasets import fetch_california_housing

In [83]:
california_housing=fetch_california_housing(as_frame=True) #as_frame =True can converts our data into DataFrame
california_housing

{'data':        MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
 0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88
 1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86
 2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85
 3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85
 4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85
 ...       ...       ...       ...        ...         ...       ...       ...
 20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48
 20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49
 20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43
 20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43
 20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37

        Longitude
 0        -122.23
 1        -122.22
 2        -122.24
 3        -122.25
 4        -122.25
 ...          ...
 20635    -121.09
 20636    -121.21
 20637    -121.22
 20638    -121.32
 20639    -121.24

 [20640 rows x 8 columns],
 'target': 0        4.526
 1        3.585
 2        3.521
 3        3.413
 4        3.422
          ...
 20635    0.781
 20636    0.771
 20637    0.923
 20638    0.847
 20639    0.894
 Name: MedHouseVal, Length: 20640, dtype: float64,
 'frame':        MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
 0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88
 1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86
 2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85
 3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85
 4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85
 ...       ...       ...       ...        ...         ...       ...       ...
 20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48
 20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49
 20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43
 20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43
 20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37

        Longitude  MedHouseVal
 0        -122.23        4.526
 1        -122.22        3.585
 2        -122.24        3.521
 3        -122.25        3.413
 4        -122.25        3.422
 ...          ...          ...
 20635    -121.09        0.781
 20636    -121.21        0.771
 20637    -121.22        0.923
 20638    -121.32        0.847
 20639    -121.24        0.894

 [20640 rows x 9 columns],
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttps://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33:291-297, 1997.\n'}

In [84]:
X=california_housing.data

X.sample(20)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
1336,5.5676,16.0,7.469428,1.015779,1606.0,3.167653,37.99,-121.88
15899,3.7813,52.0,5.057756,1.026403,1405.0,2.318482,37.75,-122.41
18428,5.6652,17.0,6.075145,0.994220,446.0,2.578035,37.26,-121.87
1906,4.3333,15.0,11.024561,2.168421,725.0,2.543860,38.76,-120.02
18635,6.0621,20.0,6.512195,1.018970,1149.0,3.113821,37.06,-122.00
10862,5.0956,21.0,5.808917,1.041401,2266.0,3.608280,33.70,-117.87
5886,3.4286,44.0,4.136086,0.992355,1676.0,2.562691,34.16,-118.33
10810,2.5301,24.0,3.452970,0.980198,1478.0,3.658416,33.64,-117.93
7284,2.1250,37.0,3.657492,1.113150,1622.0,4.960245,33.98,-118.24
8569,5.4088,27.0,4.711656,1.156442,553.0,1.696319,33.90,-118.43
12715,6.3406,41.0,7.601770,1.076696,913.0,2.693215,38.58,-121.39
20072,1.6021,29.0,4.560000,1.074545,1112.0,2.021818,37.98,-120.37
11520,15.0001,14.0,8.354232,1.037618,964.0,3.021944,33.72,-118.06
9019,8.0137,9.0,7.734673,1.041211,12873.0,3.274739,34.16,-118.78
1419,6.1359,16.0,3.157895,0.526316,65.0,3.421053,37.97,-122.05
10518,6.3790,12.0,7.819398,1.167224,1543.0,2.580268,33.51,-117.71
4006,6.0192,33.0,7.046229,1.107056,1116.0,2.715328,34.16,-118.63
14794,3.0217,26.0,4.146341,0.942073,869.0,2.649390,32.58,-117.12
14585,5.5277,30.0,5.781903,0.941995,1250.0,2.900232,32.84,-117.19
11512,4.2287,32.0,3.974609,1.015625,934.0,1.824219,33.74,-118.10

In [85]:
y=california_housing.target
y

0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: MedHouseVal, Length: 20640, dtype: float64

In [86]:
california_housing.feature_names

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [87]:
print(california_housing.DESCR)  #DECR is the attribute that prints the description of the dataset and connects wth the function(fetch_california_housing),that helps us for modeling.

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

:Number of Instances: 20640

:Number of Attributes: 8 numeric, predictive attributes and the target

:Attribute Information:
    - MedInc        median income in block group
    - HouseAge      median house age in block group
    - AveRooms      average number of rooms per household
    - AveBedrms     average number of bedrooms per household
    - Population    block group population
    - AveOccup      average number of household members
    - Latitude      block group latitude
    - Longitude     block group longitude

:Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived from the 1990 U.S. census, using one row per census
block group. A block group is the smallest geographical unit for which the U.S.
Census Bureau publishes sample data (a block group typically has a population
of 600 to 3,000 people).

A household is a group of people residing within a home. Since the average
number of rooms and bedrooms in this dataset are provided per household, these
columns may take surprisingly large values for block groups with few households
and many empty houses, such as vacation resorts.

It can be downloaded/loaded using the
:func:`sklearn.datasets.fetch_california_housing` function.

.. rubric:: References

- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,
  Statistics and Probability Letters, 33:291-297, 1997.

In [88]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=0)

### Additional Step: Scaling the Data:Standard Scaler

In [89]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [90]:
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)            #we applying this because we see in the data that we have differnent ranges there in our data.

In [91]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,r2_score

lr=LinearRegression()
lr.fit(X_train,y_train)
y_train_pred=lr.predict(X_train)
y_test_pred=lr.predict(X_test)
print(mean_absolute_error(y_train,y_train_pred))
print(f"Train Score:{r2_score(y_train,y_train_pred)}")
print(f"Test Score:{lr.score(X_test,y_test)}") #Score is the builtin function of our model

0.5293466964613609
Train Score:0.6112941337977223
Test Score:0.5926087785518777

In [92]:
#Lets we can applying Ridge regression there
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
#Model
ridge=Ridge()
#Model Train
ridge.fit(X_train,y_train)
#Model Prediction
y_train_pred=ridge.predict(X_train)
#Error
print(f"Training Score Ridge:{r2_score(y_train,y_train_pred)}")
print(f"Testing Score Ridge:{ridge.score(X_test,y_test)}")

Training Score Ridge:0.6112940497004167
Testing Score Ridge:0.5926018458652451

## Grid Search

From grid search we can apply many of alpha values and get the best alpha value that scores best.

In [93]:
from sklearn.model_selection import GridSearchCV
#List of Hyperparameters
param_grid={"alpha":[0.0001,0.001,0.01,0.1,1,10,100,1000]}
# model ridge with grid search
ridge_cv=GridSearchCV(ridge,param_grid=param_grid,cv=2)  #cv is cross validation 
#Model train
ridge_cv.fit(X_train,y_train)
#model predict on training data 
y_pred_train=ridge_cv.predict(X_train)
#model error on training data
print(mean_absolute_error(y_train,y_pred_train))
print(mean_squared_error(y_train,y_pred_train))
#model performance on train data
print(r2_score(y_train,y_pred_train))
#model best hyperparameter on training data
print(ridge_cv.best_estimator_)

0.529296304818502
0.5173113317241099
0.6112858716774313
Ridge(alpha=10)

In [94]:
y_pred_test=ridge_cv.predict(X_test)
#model error on testing data
print(mean_absolute_error(y_test,y_pred_test))
print(mean_squared_error(y_test,y_pred_test))
#model performance of testing data
print(r2_score(y_test,y_pred_test))
#model best hyperparameter on testing data
print(ridge_cv.best_estimator_)

0.5361685487385809
0.5432493326571125
0.5925334988613886
Ridge(alpha=10)

In [95]:
#Applying Lasso 
from sklearn.linear_model import Lasso
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
lasso=Lasso()

#For Training
lasso.fit(X_train,y_train)
y_pred_train=lasso.predict(X_train)
#model error on training data
print(mean_absolute_error(y_train,y_pred_train))
print(mean_squared_error(y_train,y_pred_train))
#model score on training data
print(r2_score(y_train,y_pred_train))

0.9102203910206986
1.3308271915828764
0.0

In [96]:
#For Testing 
y_pred_test=lasso.predict(X_test)
print(mean_absolute_error(y_test,y_pred_test))
print(mean_squared_error(y_test,y_pred_test))
print(r2_score(y_test,y_pred_test))

0.9149721332821296
1.3332378775677824
-8.108632143510874e-07

## Applying GridSearch and cross Validation for Best Alpha Value

In [97]:
param_grid={"alpha":[0.000000001,0.0001,0.001,0.01,0.1,10,100,1000]}

In [98]:
from sklearn.model_selection import GridSearchCV

In [99]:
lasso_cv=GridSearchCV(lasso,param_grid=param_grid,cv=3)

In [100]:
lasso_cv.fit(X_train,y_train)

GridSearchCV(cv=3, estimator=Lasso(),
             param_grid={'alpha': [1e-09, 0.0001, 0.001, 0.01, 0.1, 10, 100,
                                   1000]})

In [101]:
y_pred_train=lasso_cv.predict(X_train)

In [102]:
print(mean_absolute_error(y_train,y_pred_train))
print(mean_squared_error(y_train,y_pred_train))
r2_score(y_train,y_pred_train)

0.529406977298366
0.5173521748858638

0.6112551816208919

In [103]:
print(lasso_cv.best_estimator_)

Lasso(alpha=0.001)

In [104]:
#For Testing
y_pred_test=lasso_cv.predict(X_test)

In [105]:
print(mean_absolute_error(y_test,y_pred_test))
print(mean_squared_error(y_test,y_pred_test))
r2_score(y_test,y_pred_test)

0.5362259325760079
0.5431229465710576

0.5926282952894404

In [107]:
house_data=pd.concat([X,y],axis=1)
house_data.corr()
#We also check from correlation,but in this when i drop weakcorrelated so it decrease the result ,so its OK

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
MedInc,1.000000,-0.119034,0.326895,-0.062040,0.004834,0.018766,-0.079809,-0.015176,0.688075
HouseAge,-0.119034,1.000000,-0.153277,-0.077747,-0.296244,0.013191,0.011173,-0.108197,0.105623
AveRooms,0.326895,-0.153277,1.000000,0.847621,-0.072213,-0.004852,0.106389,-0.027540,0.151948
AveBedrms,-0.062040,-0.077747,0.847621,1.000000,-0.066197,-0.006181,0.069721,0.013344,-0.046701
Population,0.004834,-0.296244,-0.072213,-0.066197,1.000000,0.069863,-0.108785,0.099773,-0.024650
AveOccup,0.018766,0.013191,-0.004852,-0.006181,0.069863,1.000000,0.002366,0.002476,-0.023737
Latitude,-0.079809,0.011173,0.106389,0.069721,-0.108785,0.002366,1.000000,-0.924664,-0.144160
Longitude,-0.015176,-0.108197,-0.027540,0.013344,0.099773,0.002476,-0.924664,1.000000,-0.045967
MedHouseVal,0.688075,0.105623,0.151948,-0.046701,-0.024650,-0.023737,-0.144160,-0.045967,1.000000