In [1]:
import pandas as pd

In [62]:
data = pd.read_csv('diabetes.csv')
data.Pregnancies.value_counts()

Pregnancies
1     135
0     111
2     103
3      75
4      68
5      57
6      50
7      45
8      38
9      28
10     24
11     11
13     10
12      9
14      2
17      1
15      1
Name: count, dtype: int64

In [3]:
data.shape

(768, 9)

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [6]:
data.duplicated().sum()

np.int64(0)

In [7]:
X = data.drop('Outcome', axis=1)
y = data.Outcome

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(X_train,y_train)

C:\Users\Teacher\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [11]:
log_reg.coef_

array([[ 0.06656611,  0.03397376, -0.01396561,  0.00427392, -0.00182287,
         0.10060969,  0.62301667,  0.03449201]])

In [12]:
y_pred_train = log_reg.predict(X_train)

In [13]:
y_pred_train

array([0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0])

In [14]:
pd.DataFrame({'Y_TRUE':y_train, 'Y_PRED':y_pred_train})

     Y_TRUE  Y_PRED
60        0       0
618       1       0
346       0       0
294       0       1
231       1       1
..      ...     ...
71        0       0
106       0       0
270       1       1
435       1       1
102       0       0

[614 rows x 2 columns]

In [15]:
correct = 0 
for t,p in zip(y_train,y_pred_train):
    if t==p:
        correct+=1
acc = correct / len(y_train) *100

In [16]:
acc

77.19869706840392

In [17]:
y_pred_test = log_reg.predict(X_test)

In [18]:
pd.DataFrame({'Y_TRUE':y_test, 'Y_PRED':y_pred_test})

     Y_TRUE  Y_PRED
668       0       0
324       0       0
624       0       0
690       0       0
473       0       0
..      ...     ...
355       1       1
534       0       0
344       0       0
296       1       0
462       0       0

[154 rows x 2 columns]

In [20]:
correct = 0 
for t,p in zip(y_test,y_pred_test):
    if t==p:
        correct+=1
acc = correct / len(y_test) *100
acc

74.67532467532467

In [21]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report

In [26]:
accuracy_score(y_train,y_pred_train)

0.7719869706840391

In [23]:
accuracy_score(y_test,y_pred_test)

0.7467532467532467

In [24]:
precision_score(y_test,y_pred_test)

0.6379310344827587

In [25]:
recall_score(y_test,y_pred_test)

0.6727272727272727

In [29]:
print(classification_report(y_train,y_pred_train))

              precision    recall  f1-score   support

           0       0.79      0.88      0.83       401
           1       0.72      0.56      0.63       213

    accuracy                           0.77       614
   macro avg       0.76      0.72      0.73       614
weighted avg       0.77      0.77      0.76       614

In [30]:
data.Outcome.value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [41]:
class_0=data[data.Outcome==0].sample(268)

In [43]:
class_1 = data[data.Outcome==1].sample(268)

In [44]:
balanced_data = pd.concat([class_0,class_1]).sample(268+268)

In [45]:
balanced_data.Outcome.value_counts()

Outcome
0    268
1    268
Name: count, dtype: int64

In [46]:
X=balanced_data.drop('Outcome',axis=1)
y = balanced_data.Outcome

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [48]:
lr = LogisticRegression()
lr.fit(X_train,y_train)

C:\Users\Teacher\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [49]:
y_pred_train = lr.predict(X_train)

In [51]:
print(classification_report(y_train,y_pred_train))

              precision    recall  f1-score   support

           0       0.74      0.74      0.74       205
           1       0.76      0.76      0.76       223

    accuracy                           0.75       428
   macro avg       0.75      0.75      0.75       428
weighted avg       0.75      0.75      0.75       428

In [52]:
y_pred_test = lr.predict(X_test)

In [53]:
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

           0       0.90      0.83      0.86        63
           1       0.78      0.87      0.82        45

    accuracy                           0.84       108
   macro avg       0.84      0.85      0.84       108
weighted avg       0.85      0.84      0.84       108

In [54]:
df = pd.read_csv('diabetes.csv')
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [55]:
X = df.drop('Outcome',axis=1)
y = df.Outcome

In [56]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(sampling_strategy='minority', random_state=42)
X,y = smote.fit_resample(X,y)

In [57]:
y.value_counts()

Outcome
1    500
0    500
Name: count, dtype: int64

In [58]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [60]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
y_train_pred = lr.predict(X_train)
print(classification_report(y_train, y_train_pred))

              precision    recall  f1-score   support

           0       0.74      0.75      0.74       401
           1       0.75      0.73      0.74       399

    accuracy                           0.74       800
   macro avg       0.74      0.74      0.74       800
weighted avg       0.74      0.74      0.74       800

C:\Users\Teacher\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [61]:
y_test_pred = lr.predict(X_test)
print(classification_report(y_test, y_test_pred))

              precision    recall  f1-score   support

           0       0.77      0.67      0.71        99
           1       0.71      0.80      0.75       101

    accuracy                           0.73       200
   macro avg       0.74      0.73      0.73       200
weighted avg       0.74      0.73      0.73       200

In [63]:
df.corr()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
Pregnancies,1.000000,0.129459,0.141282,-0.081672,-0.073535,0.017683,-0.033523,0.544341,0.221898
Glucose,0.129459,1.000000,0.152590,0.057328,0.331357,0.221071,0.137337,0.263514,0.466581
BloodPressure,0.141282,0.152590,1.000000,0.207371,0.088933,0.281805,0.041265,0.239528,0.065068
SkinThickness,-0.081672,0.057328,0.207371,1.000000,0.436783,0.392573,0.183928,-0.113970,0.074752
Insulin,-0.073535,0.331357,0.088933,0.436783,1.000000,0.197859,0.185071,-0.042163,0.130548
BMI,0.017683,0.221071,0.281805,0.392573,0.197859,1.000000,0.140647,0.036242,0.292695
DiabetesPedigreeFunction,-0.033523,0.137337,0.041265,0.183928,0.185071,0.140647,1.000000,0.033561,0.173844
Age,0.544341,0.263514,0.239528,-0.113970,-0.042163,0.036242,0.033561,1.000000,0.238356
Outcome,0.221898,0.466581,0.065068,0.074752,0.130548,0.292695,0.173844,0.238356,1.000000

In [65]:
df = df.drop(['BloodPressure','SkinThickness'],axis=1)

In [66]:
df

,Pregnancies,Glucose,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,0,33.6,0.627,50,1
1,1,85,0,26.6,0.351,31,0
2,8,183,0,23.3,0.672,32,1
3,1,89,94,28.1,0.167,21,0
4,0,137,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...
763,10,101,180,32.9,0.171,63,0
764,2,122,0,36.8,0.340,27,0
765,5,121,112,26.2,0.245,30,0
766,1,126,0,30.1,0.349,47,1
767,1,93,0,30.4,0.315,23,0

In [67]:
from sklearn.preprocessing import MinMaxScaler

In [69]:
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(df)
scaled_data = pd.DataFrame(data=scaled_data, columns=df.columns)

In [70]:
scaled_data

,Pregnancies,Glucose,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,0.352941,0.743719,0.000000,0.500745,0.234415,0.483333,1.0
1,0.058824,0.427136,0.000000,0.396423,0.116567,0.166667,0.0
2,0.470588,0.919598,0.000000,0.347243,0.253629,0.183333,1.0
3,0.058824,0.447236,0.111111,0.418778,0.038002,0.000000,0.0
4,0.000000,0.688442,0.198582,0.642325,0.943638,0.200000,1.0
...,...,...,...,...,...,...,...
763,0.588235,0.507538,0.212766,0.490313,0.039710,0.700000,0.0
764,0.117647,0.613065,0.000000,0.548435,0.111870,0.100000,0.0
765,0.294118,0.608040,0.132388,0.390462,0.071307,0.150000,0.0
766,0.058824,0.633166,0.000000,0.448584,0.115713,0.433333,1.0
767,0.058824,0.467337,0.000000,0.453055,0.101196,0.033333,0.0

In [71]:
X= scaled_data.drop('Outcome', axis=1)
y = scaled_data.Outcome

In [75]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(sampling_strategy='minority', random_state=42)
X,y = smote.fit_resample(X,y)

In [76]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [77]:
lr_scaled = LogisticRegression()

In [78]:
lr_scaled.fit(X_train, y_train)

LogisticRegression()

In [79]:
print(classification_report(y_train, lr_scaled.predict(X_train)))

              precision    recall  f1-score   support

         0.0       0.73      0.77      0.75       401
         1.0       0.76      0.71      0.74       399

    accuracy                           0.74       800
   macro avg       0.74      0.74      0.74       800
weighted avg       0.74      0.74      0.74       800

In [80]:
print(classification_report(y_test, lr_scaled.predict(X_test)))

              precision    recall  f1-score   support

         0.0       0.73      0.72      0.72        99
         1.0       0.73      0.74      0.74       101

    accuracy                           0.73       200
   macro avg       0.73      0.73      0.73       200
weighted avg       0.73      0.73      0.73       200